version: "3.8"

services:
  photo-dashboard:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_GOOGLE_SHEETS_API_KEY=${VITE_GOOGLE_SHEETS_API_KEY}
      - VITE_GOOGLE_SHEETS_SPREADSHEET_ID=${VITE_GOOGLE_SHEETS_SPREADSHEET_ID}
      - VITE_GOOGLE_SHEETS_RANGE=${VITE_GOOGLE_SHEETS_RANGE}
    env_file:
      - .env
    stdin_open: true
    tty: true
